const COLOR_MAPPING: { [key: string]: string } = {
  q: 'moccasin',
  w: 'moccasin',
  e: 'moccasin',
  r: 'moccasin',
  t: 'moccasin',
  y: 'moccasin',
  u: 'lightgray',
  i: 'lightgray',
  o: 'lightgray',
  p: 'lightgray',
  a: 'lightgray',
  s: 'lightgray',
  d: 'lightpink',
  f: 'lightpink',
  g: 'lightpink',
  h: 'lightpink',
  j: 'lightpink',
  k: 'lightpink',
  l: 'lightsteelblue',
  z: 'lightsteelblue',
  x: 'lightsteelblue',
  c: 'lightsteelblue',
  v: 'lightsteelblue',
  b: 'lightsteelblue',
  '1': 'lightbrown',
  '2': 'lightbrown',
  '3': 'lightbrown',
  '4': 'lightbrown',
  '5': 'lightbrown',
  '6': 'lightgreen',
  '7': 'lightgreen',
  '8': 'lightgreen',
  '9': 'lightgreen',
  '0': 'lightgreen',
}

export const generatePlayerColor = (wallet: string) => COLOR_MAPPING[wallet[0].toLowerCase()]
